/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/{app.component.html, app.component.ts}",
    "./src/app/navbar/{navbar.component.html, navbar.component.ts}",
    "./src/app/navbar/icon-badge/{icon-badge.component.html, icon-badge.component.ts}",
    "./src/app/account/{account.component.html, account.component.ts}",
    "./src/app/account/login/{login.component.html, login.component.ts}",
    "./src/app/account/signup/{signup.component.html, signup.component.ts}",
    "./src/app/account/myaccount/{myaccount.component.html, myaccount.component.ts}",
    "./src/app/footer/{footer.component.html, footer.component.ts}",
    "./src/app/account/error/{error.component.html, error.component.ts}",
    "./src/app/home/{home.component.html, home.component.ts}",
    "./src/app/home/home-main/{home-main.component.html, home-main.component.ts}",
    "./src/app/home/home-category/{home-category.component.html, home-category.component.ts}",
    "./src/app/home/home-trending/{home-trending.component.html, home-trending.component.ts}",
    "./src/app/home/home-products/{home-products.component.html, home-products.component.ts}",
    "./src/app/collections/{collections.component.html, collections.component.ts}",
    "./src/app/products/{products.component.html, products.component.ts}",
    "./src/app/products/main-products/{main-products.component.html, main-products.component.ts}",
    "./src/app/products/main-products/all-main-products/{all-main-products.component.html, all-main-products.component.ts}",
    "./src/app/products/main-products/main-products-nav/{main-products-nav.component.html, main-products-nav.component.ts}",
    "./src/app/products/main-products/main-products-nav/main-products-nav-card/{main-products-nav-card.component.html, main-products-nav-card.component.ts}",
    "./src/app/products/main-products/main-products-nav/main-product-nav-dropdown/{main-product-nav-dropdown.component.html, main-product-nav-dropdown.component.ts}",
    "./src/app/products/main-products/all-main-products/product-cards/{product-cards.component.html, product-cards.component.ts}",
    "./src/app/products/product-page/product-details/{product-details.component.html, product-details.component.ts}",
    "src/app/icon/{icon.component.html, icon.component.ts}",
    "./src/app/social-media/{social-media.component.html, social-media.component.ts}",
    "./src/app/products/product-page/product-details-mid/{product-details-mid.component.html, product-details-mid.component.ts}",
    "./src/app/products/product-page/product-details-mid/description/{description.component.html, description.component.ts}",
    "./src/app/products/product-page/product-details-mid/custom-tab/{custom-tab.component.html, custom-tab.component.ts}",
    "./src/app/products/product-page/product-details-mid/reviews/{reviews.component.html, reviews.component.ts}",
    "./src/app/account/myaccount/dashboard/{dashboard.component.html, dashboard.component.ts}",
    "./src/app/account/myaccount/dashboard/update-modal/{update-modal.component.html, update-modal.component.ts}",
    "./src/app/wishlist/{wishlist.component.html, wishlist.component.ts}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

